;  Copyright (c) 1997-2026 Forest Edge Software
;                See LICENSE for applicable MIT license information.
;
;  Initialization file for eVAX
;

;
;  Initialize memory with 8mb of physical RAM
;  (the parameter is count of 512b pages)
;

init/vax ^d16384

if defined("console$arg_file" ) then set noverbose

;
;   Create page tables for the VAX phaysical memory. 
;   You can allocate more tables than will fit in
;   physical memory; virtual memory support sparse
;   memory maps. There is no support for paged 
;   backing store, though, so you can exhaust the
;   physical memory by allocaint too many physical
;   pages.

vminit /p0=16384 /p1=8192 /s0=8192 /ksp=20

;	Load the console ROM into ROM storage, if there is one found.
;	Also allocate the NVRAM storage area.
;

load/rom/noerror
load/nvram/noerror

;	Assemble the microkernel

print " "
asm  "kernel.asm"
clear sym/all


set quantum 1
go exe$initialize

set debug nouserhalt
set debug process

print " "

; Create devices

define/device tta0/devclass=term/devtype=vt100/devbufsiz=80

; TT and SYS$INPUT/OUTPUT/ERROR/COMMAND are predefined as _TTA0:.

; If there was a command line argument, assume it is the full text of the
; command to run, and do it.  Alternatively, a command could be put on
; the INCLUDE/COMMAND which would be run, and use substitution operators
; to get parts of the command.  Note that if there is a command line arg,
; then this command exits the emulator when it's done.  If you just want
; to process the command and not exit the emulator, then just use a
; substition operator like &&CONSOLE$ARG_CMD to run the command.

include/command_line
