// Command mkdefs writes internal/bootdata/files/starletdef.mar: the
// $xxxDEF symbol definition macros of govax's own STARLET.MLB
// (docs/PHASE-32.md, subtask 4). It's run by "go generate
// ./internal/bootdata", from that directory, before mkstarlet builds the
// library.
//
// Which names each macro defines, and their values, come from
// testdata/mar/rms/defined.txt: what real VAX MACRO made of govax's
// definition probes, one $xxxDEF and a .LONG of each candidate name
// (testdata/mar/rms/decode.go). The macros are generated from that list,
// not written from VMS's own.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/tucats/govax/internal/bootdata"
)

// defined is testdata/mar/rms/defined.txt, from internal/bootdata.
var defined = filepath.Join("..", "..", "testdata", "mar", "rms", "defined.txt")

var (
	headerRE = regexp.MustCompile(`^# \$([A-Z0-9]+)DEF$`)
	valueRE  = regexp.MustCompile(`^([A-Z0-9_$.]+) = 0x([0-9a-f]+)$`)
)

// macro is one $xxxDEF macro: its family (FAB, SS, ...) and the names it
// defines with their values, in defined.txt's (sorted) order.
type macro struct {
	family string
	names  []string
	values []string
}

func main() {
	f, err := os.Open(defined)
	if err != nil {
		fail(err)
	}
	defer f.Close()

	var macros []*macro

	s := bufio.NewScanner(f)
	for s.Scan() {
		line := s.Text()

		if m := headerRE.FindStringSubmatch(line); m != nil {
			macros = append(macros, &macro{family: m[1]})

			continue
		}

		if m := valueRE.FindStringSubmatch(line); m != nil && len(macros) > 0 {
			cur := macros[len(macros)-1]
			cur.names = append(cur.names, m[1])
			cur.values = append(cur.values, strings.ToUpper(m[2]))
		}
	}

	if err := s.Err(); err != nil {
		fail(err)
	}

	var b strings.Builder

	b.WriteString(`; STARLETDEF.MAR: govax's $xxxDEF symbol definition macros.
;
; Generated by internal/bootdata/mkdefs from testdata/mar/rms/defined.txt
; (docs/PHASE-32.md, subtask 4): each macro defines the names, and the
; values, real VAX MACRO showed its VMS 7.3 namesake defining. Don't edit
; it: run "go generate ./internal/bootdata".
;
; $xxxDEF [GLOBAL]
;	Define the names, as local symbols, or as global ones when the
;	argument is GLOBAL. They are defined in the absolute psect $ABS$,
;	and the psect in use before is restored. A second call defines
;	nothing new. The names are defined under .ENABLE SUPPRESSION, so
;	that a listing's symbol table shows only the ones the program
;	used, as real MACRO's does (docs/PHASE-29.md, subtask 6); MACRO
;	can't save .ENABLE's settings, so SUPPRESSION is left disabled.
`)

	for _, m := range macros {
		if len(m.names) == 0 {
			continue
		}

		name := "$" + m.family + "DEF"
		guard := "$$$" + m.family + "DEF"

		fmt.Fprintf(&b, "\n\t.MACRO\t%s\tGBL\n", name)
		fmt.Fprintf(&b, "\t.IF\tNOT_DEFINED\t%s\n", guard)
		b.WriteString("\t.SAVE\tLOCAL_BLOCK\n\t.PSECT\t$ABS$,ABS\n\t.ENABLE\tSUPPRESSION\n")
		b.WriteString("\t.IF\tIDENTICAL\t<GBL>,<GLOBAL>\n")

		for i, n := range m.names {
			fmt.Fprintf(&b, "%s == ^X%s\n", n, m.values[i])
		}

		b.WriteString("\t.IFF\n")

		for i, n := range m.names {
			fmt.Fprintf(&b, "%s = ^X%s\n", n, m.values[i])
		}

		b.WriteString("\t.ENDC\n")
		fmt.Fprintf(&b, "%s = 1\n", guard)
		b.WriteString("\t.DISABLE\tSUPPRESSION\n\t.RESTORE\n\t.ENDC\n")
		fmt.Fprintf(&b, "\t.ENDM\t%s\n", name)
	}

	if err := os.WriteFile(filepath.Join("files", bootdata.StarletDefSource), []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "mkdefs:", err)
	os.Exit(1)
}
