/********************************************************************************************************************************/
/* Created: 24-NOV-1996 13:48:42 by OpenVMS SDL EV1-33     */
/* Source:  24-NOV-1996 13:46:25 _$22$DIA11:[BUILD.SDL]RMSDEF.SDI;1 */
/********************************************************************************************************************************/
/*** MODULE $RMSDEF ***/
#ifndef __RMSDEF_LOADED
#define __RMSDEF_LOADED 1
 
#pragma nostandard
 
#ifdef __cplusplus
    extern "C" {
#define __unknown_params ...
#else
#define __unknown_params
#endif
 
#if !defined(__VAXC) && !defined(VAXC)
#define __struct struct
#define __union union
#else
#define __struct variant_struct
#define __union variant_union
#endif
 
/*                                                                          */
/* This SDL File Generated by VAX-11 Message V04-00 on 24-NOV-1996 12:29:27.40 */
/*                                                                          */
/*	.TITLE	RMSDEF -RMS COMPLETION CODES                                */
/***************************************************************************** */
/**									    * */
/**  COPYRIGHT (C) 1978, 1980, 1982, 1984 BY				    * */
/**  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    * */
/**  ALL RIGHTS RESERVED.						    * */
/** 									    * */
/**  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   * */
/**  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   * */
/**  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   * */
/**  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   * */
/**  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   * */
/**  TRANSFERRED.							    * */
/** 									    * */
/**  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   * */
/**  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   * */
/**  CORPORATION.							    * */
/** 									    * */
/**  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   * */
/**  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    * */
/** 		     							    * */
/**									    * */
/***************************************************************************** */
/*++                                                                        */
/* FACILITY: RMS                                                            */
/*                                                                          */
/* ABSTRACT:                                                                */
/*                                                                          */
/*	THIS MODULE DEFINES ALL RMS COMPLETION CODES.                       */
/*                                                                          */
/* ENVIRONMENT:                                                             */
/*                                                                          */
/*	THE MESSAGE TRANSLATOR MUST BE USED TO CONVERT RMSDEF.MSG INTO      */
/*	RMSDEF.SDL.  THE SDL TRANSLATOR MUST THEN BE USED TO CONVERT        */
/*	RMSDEF.SDL INTO RMSDEF.MAR (AND RMSDEF.B32).                        */
/*                                                                          */
/* AUTHOR: LEO F. LAVERDURE,	CREATION DATE:  10-DEC-1976                 */
/*                                                                          */
/* MODIFIED BY:                                                             */
/*                                                                          */
/*	X-15    EMW0085	     ELINOR M. WOODS		 15-MAR-1996        */
/*	        PW INTEGRATION:  REMOVE NEW ALTERNATE SUCCESS STATUS:       */
/*	        RMS$_OK_URECEOF ADDED BY X-14.  ENDED UP NOT NEEDED.        */
/*                                                                          */
/*	X-14    WDBPI1B      WALTER D. BLASCHUK, JR.      5-JAN-1996        */
/*		MERGE IN OPENVMS AXP GRYPHON CHANGE:                        */
/*                                                                          */
/*       	X-8     WDBPI1      WALTER D. BLASCHUK, JR.     19-DEC-1995 */
/*               PATHWORKS INTEGRATION: ADD NEW ALTERNATE SUCCESS           */
/*               STATUS: RMS$_OK_URECEOF <UNTERMINATED STREAM RECORD AT     */
/*               EOF SUCCESSFULLY READ>.  THIS SYMBOL SIGNIFIES THAT AN     */
/*               END-OF-FILE MARKER WAS ENCOUNTERED AND THERE WAS DATA      */
/*               IN THE BUFFER.  THIS OCCURS WHEN THE LAST RECORD OF A      */
/*               SEQUENTIAL STREAM FILE DOES NOT HAVE A TERMINATING         */
/*               CHARACTER.  THIS IS A SUCCESS STATUS AND DOES NOT HAVE     */
/*               A STV STATUS ASSOCIATED WITH IT.                           */
/*                                                                          */
/*	X-13	EMW0023		ELINOR M. WOODS		04-AUG-1994         */
/*		RMS$_KRF CAN BE RETURNED BY $CONNECT OR $REWIND, AS         */
/*		WELL AS $GET/$FIND.  MAKE TEXT ASSOCIATED WITH KRF          */
/*		STATUS MORE GENERIC BY REMOVING "for $GET/$FIND."           */
/*                                                                          */
/*	X-12	EMW0026		ELINOR M. WOODS		15-JUN-1994         */
/*		[VSC RE-IDENT]                                              */
/*		ADD ONE NEW USER-REPORTABLE STATUS:  NXR                    */
/*		<nonexistent record>.  THIS STATUS VALUE IS USED            */
/*		AS AN STV ASSOCIATED WITH RNF STATUS (STS), AND IS          */
/*		REPORTED FOR AN EXACT KEY MATCH OF A SECONDARY KEY          */
/*		IF THE SECONDARY KEY ENTRY POINTS TO A NONEXISTENT          */
/*		PRIMARY DATA RECORD IN DISK FILE.  NOTE:  RNF ERROR         */
/*		STATUS PRE-EXISTED AS ERROR CODE WITHOUT STV.               */
/*                                                                          */
/*               DEE RYAN                                30-SEP-1993        */
/*               CORRECTED USE OF DIGITAL PRODUCT NAMES.                    */
/*                                                                          */
/*	X-10	EMW0019		ELINOR M. WOODS		21-SEP-1993         */
/*		ADD ONE NEW USER-REPORTABLE ERROR STATUS (WITH AN           */
/*		ASSOCIATED STV): NETBTS.  RELOCATE NEW IDXSEARCH STATUS     */
/*		(SEE X-9) FROM "ERROR with STV" SECTION TO "ERROR WITHOUT   */
/*		STV" section.  Expand "WITH STV' AND "without STV"          */
/*		COMMENTS TO CLARIFY DIFFERENCE BETWEEN TWO.                 */
/*                                                                          */
/*	X-9	EMW0016		ELINOR M. WOODS		10-AUG-1993         */
/*		TO SUPPORT NEW KEY-LESS-THAN FUNCTIONALITY, ADDITION        */
/*		OF ONE USER-REPORTABLE ERROR STATUS:  IDXSEARCH (WITH       */
/*		AN ASSOCIATED STV), AND TWO NEW RMS-INTERNAL ERROR          */
/*		STATUSES:  LSCAN AND ROOTSRCH (WITH NO ASSOCIATED STV).     */
/*                                                                          */
/*		MODIFY SEVERITY OF TWO DTF ERROR CODES (DTFACC AND          */
/*		DTFCRE) FROM FATAL TO ERROR, AS REQUESTED BY DTF            */
/*		FACILITY.		                                    */
/*                                                                          */
/*	X-8	JM0012		JOHN MUNZER		11-NOV-1992         */
/*		CHANGE TEXT FOR RMS$_LNE.                                   */
/*                                                                          */
/*	X-7	JM0006		JOHN MUNZER		17-APR-1992         */
/*		ADD !XL PARAMETER TO RMS$_BUG TO REPORT R2.                 */
/*                                                                          */
/*	X-33	LSS0154		LEONARD S. SZUBOWICZ	 4-APR-1990         */
/*		ALTER TEXT AND FAO PARAMETERS OF RMS$_RUH AND RMS$_BUG      */
/*		CONDITION VALUES FOR RMS/DDTM SUPPORT.                      */
/*                                                                          */
/*	X-32	PJH		PAUL J. HOULIHAN	17-JAN-1990         */
/*		CHANGE TEXT FOR RMS$_INCOMPSHR ERROR MESSAGE.               */
/*                                                                          */
/*	X-31	LSS0130		LEONARD S. SZUBOWICZ	12-OCT-1989         */
/*		MERGE OF RMS/DDTM GENERATION X-30D2.                        */
/*		ADD GENERAL DDTM_ERR ERROR MESSAGE FOR DDTM SERVICE FAILURES; */
/*		STV WILL CONTAIN THE FAILING SYSTEM SERVICE CONDITION VALUE. */
/*                                                                          */
/*	X-30	LSS0080		LEONARD S. SZUBOWICZ	06-OCT-1988         */
/*		ADD RMS$_OK_ACT MESSAGE FOR USE BY FUTURE WORK TO $DISPLAY. */
/*		THIS IS PART OF LATENT SUPPORT FOR RMS/DDTM.                */
/*                                                                          */
/*	X-29	GJA0080		GARY J. ALLISON		06-JUN-1988         */
/*		CHANGE TEXT OF SEMANTICS MESSAGE.                           */
/*                                                                          */
/*	X-28	GJA0072		GARY J. ALLISON		02-MAR-1988         */
/*		ADD EXT_ERR, OPNOTSUP, EXTNOTFOU, AND SEMANTICS MESSAGES.   */
/*                                                                          */
/*	X-27	PMV0072		PETER M. VATNE		08-OCT-1987         */
/*		CHANGE RMS$_NOJNLLIC TO RMS$_JNLNOTAUTH.                    */
/*                                                                          */
/* 	X-26	LSS0057		LEONARD S. SZUBOWICZ	15-SEP-1987         */
/*		CHANGE TEXT FOR THE RMS$_OK_DUP STATUS SUCH THAT THE MESSAGE */
/*		IS APPLICABLE TO $GET AS WELL AS $PUT.                      */
/*                                                                          */
/*	X-25	PMV0068		PETER M. VATNE		11-SEP-1987         */
/*		ADD RMS$_NOJNLLIC, NO RMS JOURNALING LICENSE, FOR LMF.      */
/*                                                                          */
/*	X-24	RNM0026		RUSSELL N. MURRAY	15-AUG-1987         */
/*		ADD RMS$_SYNCH MESSAGE FOR NOTIFICATION OF SYNCHRONOUS      */
/*		COMPLETION.                                                 */
/*                                                                          */
/*	X-23	JEJ0479		JAMES E JOHNSON		13-AUG-1987         */
/*		ADD RMS$_IVATRACE MESSAGE.                                  */
/*                                                                          */
/*	X-22	PMV0061		PETER M. VATNE		03-AUG-1987         */
/*		CHANGE RESERVED MESSAGE RMS$_BUG_XX5 TO RMS$_BUG_RU_COMMIT_FAIL */
/*		TO CORRESPOND TO POSITIVE RMS BUGCHECK FTL$_RU_COMMIT_FAIL. */
/*                                                                          */
/* 	X-21	LSS0042		LEONARD S. SZUBOWICZ	13-MAY-1987         */
/*		CHANGE RESERVED MESSAGE RMS$_BUG_XX4 TO RMS$_BUG_RU_ABORT_FAIL */
/*		TO CORRESPOND TO POSITIVE RMS BUGCHECK FTL$_RU_ABORT_FAIL   */
/*	                                                                    */
/*	X-20	SAD0034		STUART A. DAVIDSON	12-MAR-1987         */
/*		DROP QUOTES FROM SNADTF MESSAGE TEXT.                       */
/*                                                                          */
/*	X-19	PJH		PAUL J. HOULIHAN	19-JAN-1987         */
/*		MERGE IN 17J1.                                              */
/*                                                                          */
/*		X-17J1	PJH		PAUL J. HOULIHAN	15-JAN-1987 */
/*			FIX SEVERAL SMALL JNL PROBLEMS.                     */
/*			ADD RMS$_BUG_FLUSH_JNL_FAILED CODE.                 */
/*                                                                          */
/*	X-18	KPS0148		KENNETH P. SIEGEL	04-DEC-1986         */
/*		ADDED SNPPF (STATISTICS MONITORING NOT SUPPORTED FOR        */
/*		PROCESS PERMANENT FILES) ERROR MESSAGE.                     */
/*                                                                          */
/*	X-17	PMV0025		PETER M. VATNE		24-NOV-1986         */
/*		ADD NEW MESSAGE, RMS$_NOTSAMEJNL.  THIS STATUS IS           */
/*		USED TO RESTRICT AI/BI WITH RU JOURNALING TO A              */
/*		SINGLE LONG-TERM JOURNAL FILE.                              */
/*                                                                          */
/*	X-16	DAS		DAVID A. SOLOMON	18-NOV-1986         */
/*		ADD NEW MESSAGE, RMS$_DELJNS. REMOVE RMS$_XCR (BY REPLACING IT */
/*		WITH A PLACEHOLDER), AS JOURNALING BITS ARE NO LONGER       */
/*		SPECIFIED IN THE $XABJNL. SLIGHT WORDING CHANGE ON DETACHED */
/*		RU RECOVERY ERROR MESSAGES.                                 */
/*                                                                          */
/*	X-15	DAS		DAVID A. SOLOMON	12-NOV-1986         */
/*		FIX ERROR IN X-5/X-6: JOURNALING VARIANT NOT MERGED         */
/*		CORRECTLY, RESULTING IN SEVERAL JOURNALING MESSAGES NUMBERS */
/*		BEING DIFFERENT IN THE MAININE THAN WHAT THEY WERE ON THE   */
/*		JOURNALING VARIANT. ALSO, MOVE NEW SNADTF MESSAGES TO RE-USE */
/*		AVAILABLE UNUSED MESSAGE NUMBERS, INSTEAD OF GENERATING NEW */
/*		ONES. FINALLY, CHANGE RMS$_BUG_ABORT TO RMS$_BUG_RU_ACTIVE. */
/*                                                                          */
/*	X-14	SAD0014		STUART A. DAVIDSON	 4-NOV-1986         */
/*		SNADTF - FIX TYPO IN DTFACC, DTFCRE                         */
/*                                                                          */
/*	X-13	SAD0014		STUART A. DAVIDSON	 3-NOV-1986         */
/*		SNADTF - FIX TYPO, ADD 2 ADDITIONAL MESSAGES.               */
/*                                                                          */
/*	X-12	JEJ0377		JAMES E JOHNSON		29-OCT-1986         */
/*		ADD NOEXTEND ERROR CODE TO FLAG FAILED RELATIVE FILE        */
/*		EXTENDS DUE TO PREVIOUS FAILURES.                           */
/*                                                                          */
/*	X-11	KPS0131		KENNETH P. SIEGEL	25-OCT-1986         */
/*		ADDED SNS ERROR CODE FOR STATISTICS NOT SUPPORT ON          */
/*		NON-DISK DEVICES.                                           */
/*                                                                          */
/*	X-10	SAD009		STUART A. DAVIDSON	06-OCT-1986         */
/*		ADD COMPLETION CODES FOR SNADTF (IBM DATA XFER)             */
/*                                                                          */
/*	X-9	GJA0003		GARY J. ALLISON		29-SEP-1986         */
/*		ADD DETACHED RECOVERY ERROR MESSAGES                        */
/*                                                                          */
/*	X-8	PMV0008		PETER M. VATNE		24-SEP-1986         */
/*		MODIFY RMS$_ACC_AIJ, RMS$_ACC_BIJ, AND RMS$_ACC_ATJ         */
/*		TO ALSO OUTPUT THE STV.                                     */
/*                                                                          */
/*	X-7	JWT0243		JIM TEAGUE		 2-SEP-1986         */
/*		ADD NEW ERRORS FOR COLLATED KEYS.                           */
/*                                                                          */
/*	X-6	GJA		GARY J. ALLISON		29-JUL-1986         */
/*		REMOVE DUPS FROM JNL MERGE.                                 */
/*                                                                          */
/*	X-5	GJA		GARY J. ALLISON		29-JUL-1986         */
/*		MERGE JOURNALING INTO MAINLINE                              */
/*                                                                          */
/*		X-3J6	DAS		DAVID A. SOLOMON	14-APR-1986 */
/*			REMOVE RMS$_RUH_FILE (USING A GENERAL RUF MESSAGE INSTEAD). */
/*			CHANGE RMS$_RUH TEXT TO NOT HAVE FAO PARAMETERS. ADD */
/*			RMS$_BUG_RURECERR.                                  */
/*	                                                                    */
/*		X-3J5	JEJ0302		JAMES E JOHNSON		 4-APR-1986 */
/*			ADD RMS$_RRF (ERROR DURING RU RECOVERY) AND         */
/*			RMS$_RUH/RMS$_RUH_FILE (USED TO FORM TEXT OF RU HANDLER ERRORS */
/*			SENT TO OPCOM).                                     */
/*	                                                                    */
/*		X-3J4	JEJ0272		JAMES E JOHNSON		11-FEB-1986 */
/*			ADD RMS$_RUF, RMS$_BUG_ABORT CODES.                 */
/*	                                                                    */
/*		X-3J3	JEJ0237		JAMES E JOHNSON		16-DEC-1985 */
/*			ADD RMS$_RUNDOWN CODE                               */
/*	                                                                    */
/*		X-3J2	JEJ0205		JAMES E JOHNSON		25-OCT-1985 */
/*			ADD JOURNAL SPECIFIC WRTJNL_XXJ ERROR CODES TO REPLACE */
/*			THE GENERIC ERRWRTJNL CODE.                         */
/*                                                                          */
/*	X-4	JEJ0216		JAMES E JOHNSON		18-NOV-1985         */
/*		MERGE X-3J2 INTO MAIN LINE FOR V4.4.                        */
/*                                                                          */
/*		X-3J2	JEJ0205		JAMES E JOHNSON		25-OCT-1985 */
/*			ADD JOURNAL SPECIFIC WRTJNL_XXJ ERROR CODES TO REPLACE */
/*			THE GENERIC ERRWRTJNL CODE.                         */
/*                                                                          */
/*	X-3	JEJ0161		JAMES E JOHNSON		 9-SEP-1985         */
/*		UPDATE RMS JOURNALING MESSAGES.                             */
/*                                                                          */
/*	X-2	JWT0212		JIM TEAGUE		 4-SEP-1985         */
/*		ADD (WHAT IS FOR NOW) AN INTERNAL STATUS CODE TO            */
/*		DIFFERENTIATE BETWEEN FINDING A DELETED RECORD (DEL)        */
/*		AND FINDING IT BUT WITH A DIFFERENT KEY (KEY_MISMATCH).     */
/*		                                                            */
/*	V03-024	RAS0314		RON SCHAEFER		21-JUN-1984         */
/*		WORK OVER THE MESSAGES ONE MORE TIME:  FIX TYPO IN OK_RNF,  */
/*		DELETE ACPEOF ERROR, DELETE WSF ERROR.                      */
/*                                                                          */
/*	V03-023	RAS0282		RON SCHAEFER		28-MAR-1984         */
/*		MINOR TEXT CHANGES AND COMMENTS ADDED.                      */
/*		DELETE RMS$_COP ERROR.                                      */
/*                                                                          */
/*	V03-022	DAS0005		DAVID SOLOMON		19-MAR-1984         */
/*		REMOVE RMS$_ECHO (NO LONGER NEEDED AS A RESULT OF NEW       */
/*		IMPLEMENTATION FOR ECHO SYS$INPUT -> SYS$OUTPUT).           */
/*                                                                          */
/*	V03-021	JWT0150		JIM TEAGUE		01-FEB-1984         */
/*		ADD RMS$_IFF FOR TRYING TO WRITE-ACCESS A FILE ON           */
/*		MAGTAPE THAT HAS NON-0 VALUE FOR ANSI BUFFER OFFSET.        */
/*                                                                          */
/*	V03-020	RAS0233		RON SCHAEFER		 9-JAN-1984         */
/*		ADD RMS$_NOVALPRS ERROR FOR $SEARCH NOT PRECEDED BY         */
/*		VALID $PARSE.                                               */
/*                                                                          */
/*	V03-019	JWT0148		JIM TEAGUE		20-DEC-1983         */
/*		ADD A JNL XAB ERROR FOR CONFLICTING RU ATTRIBUTES           */
/*		ON $CREATE: RMS$_XCR.                                       */
/*                                                                          */
/*	V03-018	RAS0171		RON SCHAEFER		28-JUL-1983         */
/*		ADD RMS$_BUSY; A STRUCTURE-LESS ERROR (R0-ONLY STATUS)      */
/*		REPLACING TEMP3.                                            */
/*                                                                          */
/*	V03-017	DAS0004		DAVID SOLOMON		28-JUN-1983         */
/*		ADD RMS$_FILEPURGED; ADD RMS$_ACPEOF FOR ZALEWSKI.          */
/*                                                                          */
/*	V03-016	KPL0007		PETER LIEBERWIRTH	 8-JUN-1983         */
/*		FIX SPELLING IN JNL ERROR MESSAGES, ADD CJF ERROR WHICH     */
/*		WILL SOON SUBSUME COP AND CQE.                              */
/*                                                                          */
/*	V03-015	DAS0003		DAVID SOLOMON		18-FEB-1983         */
/*		ADD XNF (REPLACING TEMP9), TMR (NEW), LWC (NEW).            */
/*                                                                          */
/*	V03-014	KBT0497		KEITH B. THOMPSON	18-FEB-1983         */
/*		ADD INCOMPSHR ERROR (REUSE OF TEMP1 SLOT)                   */
/*                                                                          */
/*	V03-013	RAS0120		RON SCHAEFER		 2-FEB-1983         */
/*		ADD ECHO PSEUDO-STATUS TO SUPPORT ECHO OF SYS$INPUT         */
/*		TO SYS$OUTPUT.                                              */
/*                                                                          */
/*	V03-012	JWH0174		JEFFRY W. HORN		24-JAN-1983         */
/*		ADD CQE AND COP ERRORS.                                     */
/*                                                                          */
/*	V03-011	KPL0006		PETER LIEBERWIRTH	 7-JAN-1983         */
/*		ADD OK_RULK FOR RECOVERY UNIT SUPPORT.                      */
/*                                                                          */
/*		ADD REENT ERROR FOR $RENAME.                                */
/*		                                                            */
/*	V03-009	JWH0153		JEFFREY W. HORN		 8-DEC-1982         */
/*		ADD NRU ERROR.                                              */
/*                                                                          */
/*	V03-008	JWH0152		JEFFREY W. HORN		 8-DEC-1982         */
/*		ADD JNS ERROR.                                              */
/*                                                                          */
/*	V03-007 MCN0002		MARIA DEL C. NASR	15-NOV-1982         */
/*		REPLACE ORD ERROR CODE ELIMINATED BY MCN0001, SINCE         */
/*		THE NETWORK CODE REFERENCES IT.                             */
/*                                                                          */
/*	V03-006 MCN0001		MARIA DEL C. NASR	26-OCT-1982         */
/*		PRINT KEY OF REFERENCE OR AREA IDENTIFICATION NUMBER        */
/*		INSTEAD OF XAB ADDRESS FOR ERRORS RETURNED DURING           */
/*		INDEXED FILE CREATION.  ALSO RENAME ALL UNUSED ERROR        */
/*		CODES TO TEMP.                                              */
/*                                                                          */
/*	V03-005	JWH0102		JEFFREY W. HORN		24-SEP-1982         */
/*		ADD RUP ERROR.                                              */
/*                                                                          */
/*	V03-004	RAS0095		RON SCHAEFER		 7-SEP-1982         */
/*		ADD OVRDSKQUOTA ERROR.                                      */
/*                                                                          */
/*	V03-002	JWH0002		JEFFREY W. HORN		26-JUL-1982         */
/*		CONVERT TO .MSG FORMAT.   ADD RUM ERROR.                    */
/*                                                                          */
/*	V03-001	JWH0001		JEFFREY W. HORN		20-JUL-1982         */
/*		ADD JNF, JOP, AND NOJ ERRORS.                               */
/*                                                                          */
/*	V02-042	KPL0005		PETER LIEBERWIRTH	 4-FEB-1982         */
/*		ADD ERROR MESSAGES RMS$_EXENQLM AND RMS$_DEADLOCK           */
/*		CORRECTLY.                                                  */
/*                                                                          */
/*	V02-041	CDS0001		C D SAETHER	24-JAN-1982                 */
/*		ADD GBC AND CRMP ERRORS.                                    */
/*                                                                          */
/*	V02-040	JAK0069		J A KRYCKA	15-JAN-1982                 */
/*		ADD SUPPORT AND NETFAIL ERROR CODES.                        */
/*                                                                          */
/*	V02-039	JAK0068		J A KRYCKA	31-DEC-1981                 */
/*		MODIFY TEXT FOR SUP, NET, BUG_DAP, AND ENV ERROR MESSAGES.  */
/*                                                                          */
/*	V02-038 LJA0001		LAURIE ANDERSON 20-DEC-1981                 */
/*		MODIFIED SOME MESSAGES TO READ BETTER.                      */
/*                                                                          */
/*	V02-037	JAK0063		J A KRYCKA	31-AUG-1981                 */
/*		ADD CRE_STM SUCCESS CODE.                                   */
/*                                                                          */
/*	V02-036	KPL0004		PETER LIEBERWIRTH	13-JAN-1981         */
/*		ADD ENQ SEVERE ERROR MESSAGE, TO INDICATE $ENQ/$DEQ FAILURE. */
/*		ALSO ADD SUCCESS CODES OK_RRL, AND OK_WAT.                  */
/*                                                                          */
/*	V02-035	REFORMAT	J A KRYCKA	30-JUL-1980                 */
/*                                                                          */
/*--                                                                        */
#define RMS$_FACILITY 1
#define RMS$V_STVSTATUS 14              /* MOVE TO BIT 14 OF THE            */
/* STATUS CODE IT INDICATES                                                 */
/* THAT STV CONTAINS A SECONDARY                                            */
/* STATUS CODE.                                                             */
#define RMS$_SUC 65537
#define RMS$_NORMAL 65537
/*+                                                                         */
/*                                                                          */
/*	SUCCESS CODES                                                       */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = 1                                                      */
#define RMS$_STALL 98305
/* (NOTE: USER NEVER RECEIVES THIS CODE)                                    */
#define RMS$_PENDING 98313
#define RMS$_OK_DUP 98321
#define RMS$_OK_IDX 98329
/*  (RECORD HAS BEEN INSERTED, BUT INDEX STRUCTURE IS NO LONGER             */
/*  OPTIMAL.)                                                               */
#define RMS$_OK_RLK 98337
/* (BECAUSE LOCKER SET RLK IN ROP FIELD WHEN RECORD WAS LOCKED.)            */
#define RMS$_OK_RRL 98345
/* (BECAUSE READER SET RRL IN ROP FIELD WHEN ACCESSING RECORD.)             */
/* (THIS CODE USED TO BE OK_RRV)                                            */
/*OK_RRV	;MSG <record was inserted successfully in primary>          */
/*  (BUT IT MAY NOT BE ACCESSIBLE VIA ONE-OR-MORE SECONDARY KEYS,           */
/*  AND NOT BY RFA ADDRESSING. FILE RE-ORGANIZATION RECOMMENDED!)           */
#define RMS$_KFF 98353
#define RMS$_OK_ALK 98361
#define RMS$_OK_DEL 98369
#define RMS$_OK_RNF 98377
#define RMS$_OK_LIM 98385
#define RMS$_OK_NOP 98393
#define RMS$_OK_WAT 98401
/* (BECAUSE WAT BIT IN ROP WAS SET AND RECORD WAS ALREADY                   */
/* LOCKED.)                                                                 */
#define RMS$_CRE_STM 98409
#define RMS$_OK_RULK 98417
#define RMS$_SYNCH 98425
#define RMS$_OK_ACT 98433
#define RMS$_OK_NOCURTID 98441
/*+                                                                         */
/*                                                                          */
/*	SUCCESS CODES PASSED THRU FROM DRIVERS AND ACP -	BIT 15 = 0  */
/*                                                                          */
/*-                                                                         */
#define RMS$_CONTROLC 67153             /* TERMINAL I/O ABORTED DUE TO CTRL/C */
#define RMS$_CONTROLO 67081
/* TERMINAL I/O ABORTED DUE TO CTRL/O                                       */
#define RMS$_CONTROLY 67089
/* TERMINAL I/O ABORTED DUE TO CTRL/Y                                       */
#define RMS$_CREATED 67097
/* FILE WAS CREATED, NOT OPENED                                             */
#define RMS$_SUPERSEDE 67121
/* CREATED FILE SUPERSEDED EXISTING VERSION                                 */
#define RMS$_OVRDSKQUOTA 67177
/* DISK USAGE EXCEEDS DISK QUOTA                                            */
#define RMS$_FILEPURGED 67193
/* CREATE FILE CAUSED OLDEST FILE                                           */
/* VERSION TO BE PURGED                                                     */
/*+                                                                         */
/*                                                                          */
/*	WARNING CODES                                                       */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = 1, BIT 14 = 0                                          */
#define RMS$_BOF 98712
#define RMS$_RNL 98720
#define RMS$_RTB 98728
#define RMS$_TMO 98736
#define RMS$_TNS 98744
#define RMS$_BES 98752
#define RMS$_PES 98760
/*+                                                                         */
/*                                                                          */
/*	ERROR CODES - WITHOUT STV (THAT IS, STV MAY BE USED BUT NO ASSOCIATED */
/*		      CONDITION CODE IS IN STV)                             */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = 1, BIT 14 = 0                                          */
#define RMS$_ACT 98906
#define RMS$_DEL 98914
#define RMS$_INCOMPSHR 98922
#define RMS$_DNR 98930
#define RMS$_EOF 98938
#define RMS$_FEX 98946
#define RMS$_FLK 98954
#define RMS$_FNF 98962
#define RMS$_PRV 98970
#define RMS$_REX 98978
#define RMS$_RLK 98986
#define RMS$_RNF 98994
/*  (RECORD NEVER WAS IN FILE, OR HAS BEEN DELETED.)                        */
#define RMS$_WLK 99002
#define RMS$_EXP 99010
#define RMS$_NMF 99018
#define RMS$_SUP 99026
/* (NOTE THAT SUPPORT HAS REPLACED SUP EXCEPT WHEN RMS CANNOT               */
/* MAP THE DAP STATUS CODE INTO A FAL STATUS CODE.)                         */
/* (NOTE ALSO THAT SUP SHOULD HAVE BEEN DEFINED AS A SEVERE                 */
/* ERROR CODE. HOWEVER, SUPPORT IS A SEVERE ERROR CODE.)                    */
#define RMS$_RSA 99034
#define RMS$_CRC 99042
#define RMS$_WCC 99050
#define RMS$_IDR 99058
#define RMS$_LWC 99066
#define RMS$_UNUSED1 99074
#define RMS$_NOVALPRS 99082
#define RMS$_KEY_MISMATCH 99090
#define RMS$_RUH 99098
#define RMS$_JND 99106
#define RMS$_BADPHASE 99114
#define RMS$_TOWDR 99122
#define RMS$_NEXDR 99130
#define RMS$_INVDRMSG 99138
#define RMS$_RU_ACTIVE 99146
#define RMS$_UNKRUFAC 99154
#define RMS$_LIMBO 99162
#define RMS$_IVATRACE 99170
#define RMS$_OPNOTSUP 99178
#define RMS$_EXTNOTFOU 99186
#define RMS$_EXT_ERR 99194
#define RMS$_SEMANTICS 99202
#define RMS$_LSCAN 99210
#define RMS$_ROOTSRCH 99218
#define RMS$_IDXSEARCH 99226
#define RMS$_NETBTS 99234
#define RMS$_NXR 99242
/* IF EXACT KEY MATCH ON SECONDARY KEY AND SECONDARY KEY                    */
/* ENTRY POINTS TO NONEXISTENT PRIMARY DATA RECORD IN                       */
/* DISK FILE.                                                               */
/*+                                                                         */
/*                                                                          */
/*	ERROR CODES - WITH STV ERROR CODE (THAT IS, STV CONTAINS AN ASSOCIATED CONDITION CODE) */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = BIT 14 = 1                                             */
#define RMS$_ACC 114690
#define RMS$_CRE 114698
#define RMS$_DAC 114706
#define RMS$_ENT 114714
#define RMS$_EXT 114722
#define RMS$_FND 114730
#define RMS$_MKD 114738
#define RMS$_DPE 114746
#define RMS$_SPL 114754
#define RMS$_DNF 114762
#define RMS$_RUF 114770
#define RMS$_WRTJNL_AIJ 114778
#define RMS$_WRTJNL_BIJ 114786
#define RMS$_WRTJNL_ATJ 114794
#define RMS$_WRTJNL_RUJ 114802
#define RMS$_RRF 114810
#define RMS$_DDTM_ERR 114818
/*+                                                                         */
/*                                                                          */
/*	SEVERE ERROR CODES - WITHOUT STV (THAT IS, STV MAY BE USED BUT NO ASSOCIATED */
/*		      	     CONDITION CODE IS IN STV)                      */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = 1, BIT 14 = 0                                          */
#define RMS$_DTFCDDREC 99308
#define RMS$_AID 99316
#define RMS$_ALN 99324
#define RMS$_ALQ 99332
#define RMS$_ANI 99340
#define RMS$_AOP 99348
#define RMS$_BKS 99356
#define RMS$_BKZ 99364
#define RMS$_BLN 99372
#define RMS$_BUG 99380
#define RMS$_BUG_DDI 99388
#define RMS$_BUG_DAP 99396
#define RMS$_BUG_RU_ACTIVE 99404
#define RMS$_BUG_RURECERR 99412
#define RMS$_BUG_FLUSH_JNL_FAILED 99420
#define RMS$_BUG_RU_ABORT_FAIL 99428
#define RMS$_BUG_RU_COMMIT_FAIL 99436
#define RMS$_BUG_XX6 99444
#define RMS$_BUG_XX7 99452
#define RMS$_BUG_XX8 99460
#define RMS$_BUSY 99468
#define RMS$_CCR 99476
#define RMS$_CHG 99484
#define RMS$_CHK 99492
#define RMS$_COD 99500
#define RMS$_CUR 99508
#define RMS$_DAN 99516
#define RMS$_DEV 99524
#define RMS$_DIR 99532
#define RMS$_DME 99540
#define RMS$_DNA 99548
#define RMS$_DTP 99556
#define RMS$_DUP 99564
#define RMS$_DVI 99572
#define RMS$_ESA 99580
#define RMS$_ESS 99588
#define RMS$_FAB 99596
#define RMS$_FAC 99604
#define RMS$_FLG 99612
#define RMS$_FNA 99620
#define RMS$_FNM 99628
#define RMS$_FSZ 99636
#define RMS$_FOP 99644
#define RMS$_FUL 99652
#define RMS$_IAL 99660
#define RMS$_IAN 99668
#define RMS$_IDX 99676
#define RMS$_IFI 99684
#define RMS$_IMX 99692
#define RMS$_IOP 99700
#define RMS$_IRC 99708
#define RMS$_ISI 99716
#define RMS$_KBF 99724
#define RMS$_KEY 99732
#define RMS$_KRF 99740
#define RMS$_KSZ 99748
#define RMS$_LAN 99756
#define RMS$_RUNDOWN 99764
#define RMS$_LNE 99772
#define RMS$_DTFCVT 99780
#define RMS$_MRN 99788
#define RMS$_MRS 99796
#define RMS$_NAM 99804
#define RMS$_NEF 99812
#define RMS$_DTFQUASYN 99820
#define RMS$_NOD 99828
#define RMS$_NPK 99836
#define RMS$_ORD 99844                  /*! NOT USED AS OF V4               */
#define RMS$_ORG 99852
#define RMS$_PBF 99860
#define RMS$_PLG 99868
#define RMS$_POS 99876
#define RMS$_DTFQUAVAL 99884
#define RMS$_QUO 99892
#define RMS$_RAB 99900
#define RMS$_RAC 99908
#define RMS$_RAT 99916
#define RMS$_RBF 99924
#define RMS$_RFA 99932
#define RMS$_RFM 99940
#define RMS$_RHB 99948
#define RMS$_RLF 99956
#define RMS$_ROP 99964
#define RMS$_RRV 99972
#define RMS$_RVU 99980
#define RMS$_RSS 99988
#define RMS$_RST 99996
#define RMS$_RSZ 100004
#define RMS$_SEQ 100012
#define RMS$_SHR 100020
#define RMS$_SIZ 100028
#define RMS$_SQO 100036
#define RMS$_DTFSESEST 100044
#define RMS$_SYN 100052
#define RMS$_TRE 100060
#define RMS$_TYP 100068
#define RMS$_UBF 100076
#define RMS$_USZ 100084
#define RMS$_VER 100092
#define RMS$_XNF 100100
#define RMS$_XAB 100108
#define RMS$_ESL 100116
#define RMS$_DTFSESTER 100124
#define RMS$_ENV 100132
#define RMS$_PLV 100140
#define RMS$_MBC 100148
#define RMS$_RSL 100156
#define RMS$_WLD 100164
#define RMS$_NET 100172                 /* (NOTE THAT NETFAIL HAS REPLACED NET EXCEPT WHEN RMS CANNOT */
/* MAP THE DAP STATUS CODE INTO A FAL STATUS CODE.)                         */
#define RMS$_IBF 100180
#define RMS$_REF 100188
#define RMS$_IFL 100196
#define RMS$_DFL 100204
#define RMS$_KNM 100212
#define RMS$_IBK 100220
#define RMS$_KSI 100228
#define RMS$_LEX 100236
#define RMS$_SEG 100244
#define RMS$_SNE 100252                 /*! NOT USED AS OF V4               */
#define RMS$_SPE 100260                 /*! NOT USED AS OF V4               */
#define RMS$_UPI 100268
#define RMS$_ACS 100276
#define RMS$_STR 100284
#define RMS$_FTM 100292
#define RMS$_GBC 100300
#define RMS$_DEADLOCK 100308
#define RMS$_EXENQLM 100316
#define RMS$_JOP 100324
#define RMS$_RUM 100332
#define RMS$_JNS 100340
#define RMS$_NRU 100348
#define RMS$_IFF 100356
#define RMS$_DTFTRATBL 100364
#define RMS$_DTFUNSTYP 100372
#define RMS$_DTFVERMIS 100380
/*+                                                                         */
/*                                                                          */
/*	ERROR CODES - WITHOUT STV                                           */
/*                                                                          */
/*	  DTFACC AND DTFCRE WERE ORIGINALLY INCLUDED IN THIS FATAL SEVERITY  */
/*	  (NO STV) GROUPING.  IN ORDER TO CHANGE THEIR SEVERITY TO ERROR    */
/*	  (NO STV) AND RETAIN THE SAME MESSAGE CODE VALUE, THE FOLLOWING    */
/*	  SHIFTS IN SEVERITY FROM FATAL TO ERROR AND THEN BACK AGAIN ARE    */
/*	  DONE, WHILE RETAINING THE SAME ORIGINAL BASE ASSOCIATED WITH EACH. */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = 1, BIT 14 = 0                                          */
#define RMS$_DTFACC 100386
/*+                                                                         */
/*                                                                          */
/*	SEVERE ERROR CODES - WITHOUT STV                                    */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = 1, BIT 14 = 0                                          */
#define RMS$_BOGUSCOL 100396
#define RMS$_ERRREADCOL 100404
#define RMS$_ERRWRITECOL 100412
#define RMS$_SNS 100420
#define RMS$_NOEXTEND 100428            /*+                                 */
/*                                                                          */
/*	ERROR CODES - WITHOUT STV                                           */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = 1, BIT 14 = 0                                          */
#define RMS$_DTFCRE 100434
/*+                                                                         */
/*                                                                          */
/*	SEVERE ERROR CODES - WITHOUT STV                                    */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = 1, BIT 14 = 0                                          */
#define RMS$_DELJNS 100444
#define RMS$_NOTSAMEJNL 100452
#define RMS$_SNPPF 100460
/*+                                                                         */
/*                                                                          */
/*	SEVERE ERRORS - WITH STV ERROR CODE (THAT IS, STV CONTAINS AN ASSOCIATED CONDITION CODE) */
/*                                                                          */
/*-                                                                         */
/* BIT 16 = BIT 15 = BIT 14 = 1                                             */
#define RMS$_ATR 114892
#define RMS$_ATW 114900
#define RMS$_CCF 114908
#define RMS$_CDA 114916
#define RMS$_CHN 114924
#define RMS$_RER 114932
#define RMS$_RMV 114940
#define RMS$_RPL 114948
#define RMS$_SYS 114956
#define RMS$_WER 114964
#define RMS$_WPL 114972
#define RMS$_IFA 114980
#define RMS$_WBE 114988
#define RMS$_ENQ 114996
#define RMS$_NETFAIL 115004
#define RMS$_SUPPORT 115012
#define RMS$_CRMP 115020
#define RMS$_DTFCFGFIL 115028
#define RMS$_REENT 115036
#define RMS$_ACC_RUJ 115044
#define RMS$_TMR 115052
#define RMS$_ACC_AIJ 115060
#define RMS$_ACC_BIJ 115068
#define RMS$_ACC_ATJ 115076
#define RMS$_DTFDEFFIL 115084
#define RMS$_DTFREGFIL 115092
#define RMS$_JNLNOTAUTH 115100
 
#ifdef __cplusplus
    }
#endif
#pragma standard
 
#endif /* __RMSDEF_LOADED */
 
